### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by SaltyFishAB** [yunzai-org/yunzaijs#2]
[YZ-V4.0.18][01:44:38.399][ERRO] Error: ENOENT: no such file or directory, scandir 'undefined/event'
    at readdirSync (node:fs:1451:3)
    at Middleware.install (file:///home/user/yunzaijs/yunzai/core/middleware/index.ts:32:21)
    at file:///home/user/yunzaijs/src/main.ts:23:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout._onTimeout (file:///home/user/yunzaijs/src/main.ts:18:3) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'undefined/event'
}

**Comment by ningmengchongshui** [comment]
根据测试。windows11是正常的。

可以检查是否是更新过程中，git出现了代码缺失，可以考虑重装。或者提供系统环境，node环境等信息。

```
[YZ-V4.0.18][22:18:54.788][INFO] 正在连接 redis://127.0.0.1:6379/0
[YZ-V4.0.18][22:18:55.107][INFO] Redis 连接成功
[YZ-V4.0.18][22:18:55.114][MARK] ----------
[YZ-V4.0.18][22:18:55.115][MARK] Package Version: icqq@0.6.10 (Released on 2024/2/4)
[YZ-V4.0.18][22:18:55.115][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
[YZ-V4.0.18][22:18:55.115][MARK] ----------
[YZ-V4.0.18][22:18:55.275][INFO] [794161769]使用协议：aPad_9.0.17.15185
[YZ-V4.0.18][22:18:55.495][MARK] 39.156.125.20:8080 connected
[YZ-V4.0.18][22:18:55.597][MARK] Welcome, 夫君真行 ! 正在加载资源...
[YZ-V4.0.18][22:18:56.045][MARK] 加载了119个好友，1个群，1个频道，0个陌生人
[YZ-V4.0.18][22:18:56.046][MARK] Yunzai V4.0.18 上线
[YZ-V4.0.18][22:18:56.406][INFO] 读取浏览器: C:/Program Files/Google/Chrome/Application/chrome.exe
[YZ-V4.0.18][22:18:56.671][INFO] 加载渲染器: puppeteer
[YZ-V4.0.18][22:18:57.079][INFO] 加载中间件: message-runtime.ts
[YZ-V4.0.18][22:18:57.083][INFO] 加载中间件: message-star-rail.ts
[YZ-V4.0.18][22:18:57.086][INFO] 加载定时器: ...
[YZ-V4.0.18][22:18:57.086][INFO] 加载插件中: ...
```
